In [1]:
import numpy as np
import numpy.linalg as LA

In [34]:
def Dprime(D0, detD0, D0bar, D1, part_index):
    # gives detD1, D1bar as output -- *without* calculating det(D1) and inv(D1).T :: ref Nandini Notes

    j0 = part_index     # particle that has moved

    Dinv = D0bar.T
    diff_pos = np.asarray((D1-D0)[:,j0])
    print(diff_pos,'diffpos')

    ek = np.zeros([len(D0),1])
    ek[j0,0] = 1

    print(ek,'ek')

    print(np.shape(ek), np.shape(Dinv), np.shape(diff_pos))

    qRatio = (1.0 + ek.T*Dinv*diff_pos)[0,0]

    print(qRatio,'qRatio')

    detD1 = qRatio*detD0

    if np.abs( detD1 ) > 0.0:       
        D1inv = Dinv - (Dinv*diff_pos*ek.T*Dinv)/qRatio       
        return detD1, D1inv.T
    else:
        return 0.0, np.eye(Np)


In [35]:
D0 = np.asmatrix([[1,2],[3,4]])
detD0 = LA.det(D0)
D0bar = LA.inv(D0).T
D1 = np.asmatrix([[11,2],[15,4]])
part_index = 0

print(D0, detD0, D0bar, D1, part_index)

print(Dprime(D0, detD0, D0bar, D1, part_index))

print( LA.det(D1), LA.inv(D1).T )

[[1 2]
 [3 4]] -2.0000000000000004 [[-2.   1.5]
 [ 1.  -0.5]] [[11  2]
 [15  4]] 0
[[10]
 [12]] diffpos
[[1.]
 [0.]] ek
(2, 1) (2, 2) (2, 1)
-6.9999999999999964 qRatio
(13.999999999999996, matrix([[ 0.28571429, -1.07142857],
        [-0.14285714,  0.78571429]]))
13.999999999999996 [[ 0.28571429 -1.07142857]
 [-0.14285714  0.78571429]]
